### ISSUE TITLE
READMEのビルドコマンド

### ISSUE THREAD

**Issue by kzthrk** [yuru7/bizin-gothic#2]
READMEファイルの記載内容について報告します。

ビルドしてインストールするものと勘違いしてビルドを試みたところ、
`& "C:\Program Files (x86)\FontForgeBuilds\bin\ffpython.exe" .\fontforge_script.py && python .\fonttools_script.py`
の部分で「トークン '&&' は、このバージョンでは有効なステートメント区切りではありません。」というエラーになったため2回に分けて実行しました。

当方の環境云々が、READMEの記載に影響しそうにないですが念のため記載しておきます。
環境　Windows 11 Pro 23H2

**Comment by yuru7** [comment]
反応遅れてすみません。

ご報告の内容は、おそらくPowerShellのバージョンに起因するものと思われます。
[PowerShell 7 からPipeline Chain Operators(&& と ||)が使える様になります | DevelopersIO](https://dev.classmethod.jp/articles/powershell-7-pipeline-chain-operator/)

手元のWindows 11で確認したところ、デフォルトインストールされているものはPowerShell 5でした。一方、任意インストールのPowerShellはバージョン7系でした。

ということで、READMEには「PowerShell 7未満の場合」としたコマンドを追記しておくこととしました。
ご報告ありがとうございました 🙇‍♂️
