### ISSUE TITLE
Nerd fontグリフの文字幅がおかしい

### ISSUE THREAD

**Issue by hamano** [yuru7/bizin-gothic#3]
たいへん気に入っており利用させていただいていますが、
linux+rxvt-unicodeという環境で多くのnerd fontがズレる問題があり調べてみました。

![urxvt](https://github.com/user-attachments/assets/ebd06538-898c-4715-9077-d0a56f7524fe)

rxvt-uniocdeはglibc localeに従って表示幅を決定し、該当文字はwidth 2で表示するようにしています。
(ちなみに既定の状態width 1だとrxvt-unicodeで該当文字は表示されません。半角幅を大幅に超えるグリフ幅の文字は表示されません)
fontforgeの一覧画面で既にズレているように見えるので、terminalの問題ではありません。

![fontforge](https://github.com/user-attachments/assets/4af495bc-b27b-431a-ad3d-c321d8bd2ce6)

コードを確認するとグリフの幅が1024に変更されており、中心からズレています。

![F113](https://github.com/user-attachments/assets/8658c070-11e9-4dbf-a8ee-90cb319b215d)

linuxユーザーとしての意見になりますが、ターミナル上で文字を半角か全角で扱うかは、libc localeやTUIアプリケーションで決定すべきことであり、フォントのグリフ幅は純粋にそのグリフの幅(字形が収まる矩形の幅)が入っていてほしいと考えています。
おそらく何らかの問題があり幅の変更を行ったのだと思いますが、どのような経緯でNFフォントのグリフ幅を変更されたのでしょうか?
また、幅の変更をオプションにするのはいかがでしょうか?

**Comment by hamano** [comment]
以下の修正で解消しています。
```
diff --git a/fontforge_script.py b/fontforge_script.py
index ff08925..9cd6bb4 100644
--- a/fontforge_script.py
+++ b/fontforge_script.py
@@ -893,7 +893,7 @@ def add_nerd_font_glyphs(jp_font, eng_font):
                     psMat.translate((half_width - nerd_glyph.width) / 2, 0)
                 )
             # 幅を設定
-            nerd_glyph.width = half_width
     # 日本語フォントにマージするため、既に存在する場合は削除する
     for nerd_glyph in nerd_font.glyphs():
         if nerd_glyph.unicode != -1:

```
![urxvt2](https://github.com/user-attachments/assets/f6a31f07-a59d-4532-9775-24657c997754)

**Comment by yuru7** [comment]
ご報告ありがとうございます。

こちら、仕様通りです。

本家Nerd Fontsには、各合成フォントごとに3つのバリエーションが同梱されています。

- 通常版 (フォント名が ～NF になっているもの。下図 fig_N1, fig_N2 参照)
- モノスペース版 (フォント名が ～NFM になっているもの。下図 fig_M1, fig_M2 参照)
- プロポーショナル版 (フォント名が ～NFP になっているもの。下図 fig_P1, fig_P2 参照)

これらのうち、Bizin Gothicのリリースに加えているものは通常版と同等の仕様になることを意識して合成しています。これは、Nerd Fontsを利用する各ツールにおいて通常版を想定して作成されることが多いであろうと判断したためです。

リリースには汎用性の高いものだけを含みたいためモノスペース版、プロポーショナル版を同梱することは今のところ考えていませんが、ビルドオプションとして用意するのはありだと思います。(モノスペース版では縮小処理など考える必要はありますが)

以下、余談。
通常版、モノスペース版、プロポーショナル版はそれぞれ一長一短あります。

- 通常版:
	- Nerd Fontsのグリフ幅はすべて半角幅で設定されているため、合成後のフォントは等幅の属性を設定できる
	- グリフのサイズはそのままなので、半角幅を超えて描画されるグリフが多い。グリフの右隣に半角スペースを入れて表示を調整しないと隣接文字と被る可能性あり
	- 表示するソフトによってはグリフ幅を超えた部分が描画できない。
- モノスペース版: 
	- Nerd Fontsのグリフ幅はすべて半角幅で設定されているため、合成後のフォントは等幅の属性を設定できる
	- 通常版と違いグリフ幅を超えないため隣接文字との被りや表示ソフトとの相性を気にする必要はないが、半角幅に収まるように縮小しているためグリフがかなり小さくなっている
- プロポーショナル版:
	- Nerd Fontsのグリフ幅はグリフによって可変のため、合成後のフォントは等幅の属性を設定できない
	- プロポーショナルフォント扱いになるため表示桁が揃わない場面が考えられる。よってターミナルとの相性は悪い
	- グリフのサイズはそのままなので、モノスペース版のように縮小され小さくなることはない

---

fig_N1 (InconsolataNF):

![image](https://github.com/user-attachments/assets/b3916a19-ae99-44d1-9535-778189ab112d)

fig_N2 (InconsolataNF):

![image](https://github.com/user-attachments/assets/2b83d970-6ac0-43ff-a4c9-c62e991d762e)

fig_M1 (InconsolataNFM):

![image](https://github.com/user-attachments/assets/62cf1d80-a6bf-4ce8-82ee-fc431b8b9c4c)

fig_M2 (InconsolataNFM):

![image](https://github.com/user-attachments/assets/52a44247-e249-4a1c-bfe6-34db6ea3b120)

fig_P1 (InconsolataNFP):

![image](https://github.com/user-attachments/assets/ded072eb-73a2-4179-99b9-02bbf347d15d)

fig_P2 (InconsolataNFP):

![image](https://github.com/user-attachments/assets/6abf5fd7-e8cf-4cac-942d-7c641823b603)

**Comment by hamano** [comment]
ご説明ありがとうございます。状況が理解できました。
とくに何か修正をしてほしい訳ではないのですが、どうあるべきか考えたいのでご意見いただければ幸いです。

NF文字(主にprivate領域)をどう扱うか、ターミナルの仕様、設定により以下のタイプに分類できます。

a) 半角の前進幅でグリフを(おおよそ)全角に描画する
b) 半角の前進幅でグリフを半角に描画する
c) 全角の前進幅でグリフを全角に描画する
d) フォントの前進幅でグリフ全体を描画する

(a)の環境にマッチするのが、`Inconsolata Nerd Font(通常版)`でありこれと同じように合成した`Bizin Gothic NF`もこの環境を前提にしているため、フォントが意図的にズレていると理解しました。
しかしご承知の通り、半角の前進幅で全角サイズのグリフを描画すると次の文字と重なるため

```
$ echo '|\uf113 |'
```

とスペースで調整する必要があります。ターミナルの機能不足、設定不足によりこのような環境が多いことは理解できますが、この環境が汎用的で望ましい姿かどうか疑問です。

(b) はオーバーラップを回避するためにNFフォントを半角に縮小、`Inconsolata Nerd Font Mono`が想定している環境と思います。
そもそも全角で描画されることを想定したグリフを半角に縮小して描画することは各オリジナルのフォントの制作者の意図に反しており、見た目も悪いので、よい方法ではないと考えます。

(c) は私が利用している環境です。
rxvt-unicode, mlterm などではコートポイント範囲で前進幅を設定可能ですのでNFフォントが利用するprivate範囲に限定して全角の前進幅を設定しています。
この環境では`Inconsolata Nerd Font Mono`や`Bizin Gothic NF`はズレてしまうのですが、
NerdFont公式の`Symbols Nerd Font Mono`では半角サイズのmonospaceではなく、BoundingBoxが正方形で全角幅で統一されていました。
rxvt-unicodeは複数フォントを指定してfallbackできるので、以下のようにして期待通りにNFフォントを利用できました。

```
$ urxvt -fn 'xft: Bizin Gothic Discord,xft: Symbols Nerd Font Mono'
```

できれば`BIZ UDゴシック`と`Symbols Nerd Font Mono`を合成したいところですが、それほど困っていない状況です。

(d)こんなターミナル環境あるのか私は知らないのですが、VSコードなどのGUIテキストエディタはこのような動作なのでプログラミング向けフォントとしては対応すべきではないかと思いました。

現状VSCodeで`Bizin Gothic Discord NF`を指定すると以下のようになります。

![vscode1](https://github.com/user-attachments/assets/80dc6001-1e23-4f3a-9b1f-856db0e23511)

これは(a)のターミナル環境と同じ状況なので仕様だと言われればそれまでですが、こちらも合成フォントを利用せず

```
"Bizin Gothic Discord", "Symbols Nerd Font Mono"
```
とフォールバックさせれば私が期待する動作になりました。

![vscode2](https://github.com/user-attachments/assets/89fad8d7-09d7-45a8-9672-d501dd3b03f6)

vscodeのターミナル環境はまた違ったロジックで前進幅を決定しているようです...

等幅の属性(isFixedPitch)についてよくわかっていません。
- つけないとなにか困ったことが起きるのでしょうか?
- 英語圏でmonospaceというとすべて半角かもしれませんが、日本語で等角フォントというと半角サイズと全角サイズのグリフが混ざっているのが通常ですようね。 このような等角フォントにisFixedPitch=1は指定できないのでしょうか?

**Comment by yuru7** [comment]
> (a)の環境にマッチするのが、Inconsolata Nerd Font(通常版)でありこれと同じように合成したBizin Gothic NFもこの環境を前提にしているため、フォントが意図的にズレていると理解しました。

ご認識合っています。

> a) 半角の前進幅でグリフを(おおよそ)全角に描画する
> ターミナルの機能不足、設定不足によりこのような環境が多いことは理解できますが、この環境が汎用的で望ましい姿かどうか疑問です。

推測の域を出ませんが、以下のような状況から、「a) 半角の前進幅でグリフを(おおよそ)全角に描画する」が標準になっているのだと思います。消極的理由ではあるものの、「ベストではないがベターな仕様」だと感じます。

- 各ターミナルソフトは最低限、ASCII範囲を始めとした半角等幅文字を基準に描画およびカーソル移動できるようになっている
- Nerd Fontsに限らず、通常言語文字においてもグリフ設定幅の外側 (幅の左側・右側に一部がはみ出る、あるいはゼロ幅だけど描画がある) に描画される場合はあるため、幅の外への描画に対応するソフトは多い
- East Asian Ambiguous Widthのように幅がUnicode仕様上で明示されていないコードポイントの文字において、カーソル前進幅を半角固定としているターミナルがある
- Unicode定義上のプライベート領域のグリフ幅はフォント実装に委ねられる (Nerd Fontsのグリフはプライベート領域に設定されている)
- Nerd Fontsグリフを半角幅に収めようとすると極端に小さくなり、判別できなくなってしまうグリフが多い

もしもフォントを表示するソフトウェア側の仕様が「グリフ個別の幅を認識し、グリフ表示幅とカーソル移動幅を正しく調整できる」として統一されていたならば、Nerd Fontsの各グリフは全角幅にして収めるようになっていたのだろうと思います。

> (b) はオーバーラップを回避するためにNFフォントを半角に縮小、Inconsolata Nerd Font Monoが想定している環境と思います。
> そもそも全角で描画されることを想定したグリフを半角に縮小して描画することは各オリジナルのフォントの制作者の意図に反しており、見た目も悪いので、よい方法ではないと考えます。

同感です。
本家での選択肢としてNFMバリエーションが同梱されているものの、使い勝手がよろしくないので使っている方は多くないと想像します。

>  c) 全角の前進幅でグリフを全角に描画する

前述の「East Asian Ambiguous Widthのように幅がUnicode仕様上で明示されていないコードポイントの文字において、カーソル前進幅を半角固定としているターミナルがある」に通ずるところかと思います。
Nerd Fontsの各グリフはUnicode上、幅が定義されていないプライベート領域を利用しているため、グリフで全角幅に設定してあっても、いわゆる「East Asian Ambiguous Width 問題」と同様のカーソル位置ずれ問題が起きるターミナルがあると推測します。


>  d) フォントの前進幅でグリフ全体を描画する
> VSコードなどのGUIテキストエディタはこのような動作なのでプログラミング向けフォントとしては対応すべきではないかと思いました。

おっしゃるように、プロポーショナルフォントはターミナル用途でなく、GUIテキストエディタ用途になってくると思います。

> 等幅の属性(isFixedPitch)についてよくわかっていません。
> - つけないとなにか困ったことが起きるのでしょうか?

まず前提として、ちょっと説明を加えます。
等幅に関係する属性値として、過去にユーザーからご報告を受けるなどを契機に、合成するときに調整してきたのは以下の3点です。

- post テーブル > isFixedPitch 値
- OS/2 テーブル > panose テーブル > bProportion 値
- OS/2 テーブル > xAvgCharWidth 値

post テーブル > isFixedPitch 値:

表示設定で等幅フォントしかリストしないエディタが一定数あります。isFixedPitch が適切でないと設定時に選択できないという問題が起こる場合があります。
参考: https://askubuntu.com/questions/1380716/how-do-i-make-gvim-detect-a-certain-font

OS/2 テーブル > panose テーブル > bProportion 値:

「panose テーブル > bProportion 値」でも、プロポーショナルか等幅かを示すフラグを設定できます。ここが適切に設定されていないと、一部のソフト上の一部の記号で、グリフに設定された文字幅を無視して描画されることがあります。ちなみにこの事象に今まで遭遇したことがあるのは、ExcelとEclipseです。
参考: https://github.com/yuru7/HackGen/issues/33

OS/2 テーブル > xAvgCharWidth 値:

「xAvgCharWidth 値」は、「フォント全体のグリフのうちゼロ幅グリフを除く、すべてのグリフ幅の平均値を設定する」とされている設定項目です。よって、欧文グリフのみの等幅フォントにおいては半角の文字幅が設定されることになります。日本語グリフも含まれる等幅フォントだと全角グリフも含まれるわけなので本来の "平均値" という考え方とは異なってしまいますが、半角英数字の半角幅を設定するのが慣例となっているようです。
もう記憶も曖昧ですが、この値は一部のソフトでグリフの表示幅として扱われるケースがあった気がします。

> - 英語圏でmonospaceというとすべて半角かもしれませんが、日本語で等角フォントというと半角サイズと全角サイズのグリフが混ざっているのが通常ですようね。 このような等角フォントにisFixedPitch=1は指定できないのでしょうか?

半角1:全角2 の幅になっている日本語等幅フォントにおいては isFixedPitch=1 を指定できます。

前述のように「等幅フォントのみ使う前提とするため、isFixedPitchを見ているエディタ」で、なおかつCJK利用を想定しているソフトウェアであれば、日本語グリフを適切な幅で扱えます。この際に「日本語グリフの前進幅は xAvgCharWidth 値 の2倍」のように表示幅、カーソル前進幅を決めているものと思われます。(テキストエディタ開発は門外漢なので確証はありませんが…)

よって、半角1:全角2 の幅になっている日本語等幅フォントにおいては、isFixedPitch=1 を指定するのが慣例です。
ただ拙作の別フォントにあるような 半角3:全角5 の幅になっているフォントにおいては、 isFixedPitch=0 としています。日本語グリフが xAvgCharWidth 値 の倍幅にはなっていないからです。

これらを鑑みて私としては、「ASCII範囲の英数字を半角の基準として、含まれるすべてのグリフが 半角1:全角2 の幅になっていること」を条件に、「isFixedPitch 値」「panose テーブル > bProportion 値」「xAvgCharWidth 値」は、等幅フォントとして設定すると良さそうと考えています。

**Comment by hamano** [comment]
ご意見ありがとうございます。

> 推測の域を出ませんが、以下のような状況から、「a) 半角の前進幅でグリフを(おおよそ)全角に描画する」が標準になっているのだと思います。消極的理由ではあるものの、「ベストではないがベターな仕様」だと感じます。

やはり私にはこれを標準とすることが受け入れがたく、`SymbolsNerdFontMono-Regular.ttf`と合成したカスタムフォントを使うことにしました。

vscodeの例で示したように「(a) 半角の前進幅でグリフを(おおよそ)全角に描画する」はNF文字の後にスペースを後置することになりますが、プログラミングの文脈で`print("\uF113")`と`print("\uF113 ")`は異なる実行結果となりますのでですので「見た目が崩れる」以上の問題が起こる気がします。

> Unicode定義上のプライベート領域のグリフ幅はフォント実装に委ねられる (Nerd Fontsのグリフはプライベート領域に設定されている)

ここは「ターミナルまたはその上のアプリケーション」と「GUIアプリ」で状況が異なるのではないかと思います。
たとえばurxvt, mlterm, vim, emacsなどではprivate領域すなわちamb witdhですのでを半角か全角の前進幅とするかはユーザーに委ねられる、vscodeのようなGUIアプリではフォント実装に委ねられる。という認識です。

NerdFontだけでなく、矢印、罫線、いわゆるJPDOCなども含めると人々がフォントに求める好みは千差万別であり、自分用のフォントを生成するしか無いのかなという気がしてきました。

いろいろとご教授頂きありがとうございました。
